name:                toothpaste
version:             0.9.1.3
github:              "githubuser/adamburkegh/toothpaste"
license:             GPL-3
author:              "Adam Burke"
maintainer:          "Adam Burke"
copyright:           "2020-2022 Adam Burke"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README 

dependencies:
- base >= 4.7 && < 5
- cmdargs >= 0.10.20 && < 2
- containers > 0.1 && < 2
- split > 0.2.3 && < 2
- xml > 1.3 && < 2
- HUnit >= 1.6.1.0 && < 2

library:
  source-dirs: src/main/haskell

executables:
  toothpaste:
    main:                Main.hs
    source-dirs:         src/main/haskell
    ghc-options:
    - -threaded
    - -fwarn-unused-imports
    - -rtsopts
    - -with-rtsopts=-N
      # - '"-with-rtsopts=-M250M -N -xc"' 
      # - -O2
    dependencies:
    - toothpaste

tests:
  toothpaste-test:
    main:                Main.hs
    source-dirs:         src/test/haskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toothpaste
    - HUnit
    - HUnit-approx

